# Site settings
title: Statson
subtitle: mathematical designs and innovations
email: loris.michel@gmail.com
description: Notre &eacute;quipe est composee de six math&eacut&eacute;maticiens fra&icirc;chement diplom&eacute;s de l'EPFL et specialis&eacute;s en probabilit&eacute;s et statistique. 
        Nous travaillons ensemble depuis maintenant trois ans et avons obtenus de bons classements a des concours de data mining et de machine learning internationaux. 
        Nos comp&eacute;tences techniques, en informatiques ainsi que nos secteurs d'expertise sont vari&eacute;s et compl&eacute;mentaires..
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown

sass:
  style: compressed
