# Site settings
title: OUR TEAM
subtitle: analytical solutions and innovation
email: loris.michel@gmail.com
description: Notre &eacute;quipe est compos&eacute;e de six math&eacute;maticiens fra&icirc;chement diplom&eacute;s de l'EPFL et specialis&eacute;s en probabilit&eacute;s et statistiques. 
        Nous travaillons ensemble depuis maintenant trois ans et avons obtenu de bons classements a des concours de data mining et de machine learning internationaux. 
        Nos comp&eacute;tences techniques en analyse de donn&eacute;es, en informatique ainsi que nos secteurs respectifs d'expertise sont vari&eacute;s et compl&eacute;mentaires.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: Lausanne
state: Vaud
country: Swizerland
phone: 

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

sass:
  style: compressed
