# Site settings
title: Notre &eacute;quipe
subtitle: solutions analytiques et innovantes
email: loris.michel@gmail.com
description: Formee a l'EPFL, l'institut technologique preponderant en Europe, 
notre equipe s'est construite autours d'un vaste pannel de projets, allant de la 
recherche medicale au marketing digital.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: Lausanne
state: Vaud
country: Swizerland
phone: 

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

sass:
  style: compressed
